service:
  name: victorfateh-backend

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  region: us-west-1
  memorySize: 256

functions:
  health:
    handler: src/handlers/health.handler
    events:
      - http:
          method: get
          path: /health
